# Generated by Django 4.2.20 on 2025-04-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
