# Generated by Django 5.2.3 on 2025-07-10 12:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, help_text='Iranian cell phone number like 09123456789.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian cell phone number (e.g., 09123456789).', regex='^09\\d{9}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with this email address already exists.'}, help_text='Email address like example@domain.com.', max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('is_verified_phone_number', models.BooleanField(default=False, help_text="Designates whether this user's phone number has been verified.", verbose_name='Verified Phone Number')),
                ('is_verified_email', models.BooleanField(default=False, help_text="Designates whether this user's Email has been verified.", verbose_name='Verified Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
