# Generated by Django 5.2.3 on 2025-06-29 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with this email address already exists.'}, help_text='Email address like example@domain.com.', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, help_text='Iranian cell phone number like 09123456789.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Iranian cell phone number (e.g., 09123456789).', regex='^09\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
