# Generated by Django 5.2.3 on 2025-08-08 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_received_product_image', models.ImageField(blank=True, null=True, upload_to='product_images/comments', verbose_name='User Received Product Image')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Rating')),
                ('description_title', models.CharField(max_length=128, verbose_name='Description Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Set True for confirmed comments (Set False for Soft Delete)', verbose_name='Active Status')),
                ('is_anonymous', models.BooleanField(default=True, help_text='User with True is anonymous', verbose_name='Anonymity Status')),
                ('is_purchased', models.BooleanField(default=True, help_text='User purchased the product or not', verbose_name='Purchased Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_date', 'description_title'],
            },
        ),
    ]
