# Generated by Django 5.2.3 on 2025-08-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_percentage_product_has_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_date', 'description_title'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
